'use client';

import { FormEvent, useState } from 'react';
import { ArrowRight, Check, Compass, Footprints, Sparkles } from 'lucide-react';

export default function CreatePage() {
  const [action, setAction] = useState('');
  const [clue, setClue] = useState('');
  const [published, setPublished] = useState(false);
  function submit(event: FormEvent) { event.preventDefault(); if (!action.trim()) return; setPublished(true); }

  return <main className="mx-auto w-full max-w-5xl px-5 pb-28 pt-8 md:px-8 md:pt-12">
    <header className="border-b border-white/[.07] pb-10"><div className="flex items-center gap-3 text-[10px] uppercase tracking-[.2em] text-zinc-500"><span className="text-zinc-200">PULSE / START</span><span>Build the next handoff</span></div><div className="mt-8 max-w-4xl"><p className="text-[10px] uppercase tracking-[.2em] text-zinc-600">A Pulse begins with an action</p><h1 className="mt-4 text-[clamp(2.8rem,6vw,5.8rem)] font-medium leading-[.94] tracking-[-.055em] text-zinc-50">What do you want<br/><span className="text-zinc-500">the next person to do?</span></h1><p className="mt-7 max-w-xl text-sm leading-7 text-zinc-400">Not a post. Not a caption. Give someone a small reason to step outside their normal routine.</p></div></header>
    <form onSubmit={submit} className="mt-12 space-y-12">
      <section className="rounded-[28px] border border-white/[.07] bg-[#101013] p-6 sm:p-9"><div className="flex items-center gap-2 text-[10px] uppercase tracking-[.18em] text-zinc-500"><Footprints size={13}/> Step 01 · The action</div><label htmlFor="action" className="mt-7 block text-2xl font-medium tracking-tight text-zinc-100">What should they actually do?</label><textarea id="action" value={action} onChange={e => { setAction(e.target.value); setPublished(false); }} maxLength={280} rows={4} autoFocus placeholder="Find a hidden detail in your town and leave the next clue..." className="mt-5 w-full resize-none rounded-2xl bg-black/20 p-5 text-lg leading-8 text-zinc-100 outline-none ring-1 ring-white/[.06] placeholder:text-zinc-700 focus:ring-white/[.14]" /><div className="mt-3 flex justify-between text-[10px] uppercase tracking-[.16em] text-zinc-600"><span>Make it specific enough to try</span><span>{action.length}/280</span></div></section>
      <section className="grid gap-6 md:grid-cols-2"><div className="rounded-[24px] border border-white/[.07] bg-[#101013] p-6"><div className="flex items-center gap-2 text-[10px] uppercase tracking-[.18em] text-zinc-500"><Compass size={13}/> Step 02 · The clue</div><label htmlFor="clue" className="mt-6 block text-lg font-medium text-zinc-200">What should the next person know?</label><textarea id="clue" value={clue} onChange={e => setClue(e.target.value)} rows={5} maxLength={500} placeholder="Give them enough context to begin. Keep the discovery alive." className="mt-4 w-full resize-none bg-transparent text-sm leading-7 text-zinc-300 outline-none placeholder:text-zinc-700" /></div><div className="rounded-[24px] border border-white/[.07] bg-[#101013] p-6"><div className="flex items-center gap-2 text-[10px] uppercase tracking-[.18em] text-zinc-500"><Sparkles size={13}/> Step 03 · The handoff</div><p className="mt-6 text-lg font-medium text-zinc-200">Your Pulse becomes real when someone else continues it.</p><div className="mt-5 rounded-2xl bg-white/[.035] p-4 text-sm leading-6 text-zinc-400">You → Next Person → Their discovery → Next clue</div><p className="mt-5 text-xs leading-5 text-zinc-600">The person who joins can respond with what they found and create the next action.</p></div></section>
      <footer className="flex flex-wrap items-center justify-between gap-5 border-t border-white/[.07] pt-7"><span className="text-xs text-zinc-600">{published ? 'Pulse staged. The handoff can begin.' : 'Keep it small. Make it possible today.'}</span><button type="submit" disabled={!action.trim()} className="inline-flex items-center gap-2 rounded-full bg-zinc-100 px-6 py-3 text-xs font-semibold uppercase tracking-[.14em] text-zinc-950 disabled:opacity-30">{published ? <Check size={15}/> : null}{published ? 'Pulse ready' : 'Start Pulse'} <ArrowRight size={15}/></button></footer>
    </form>
  </main>;
}
