'use client';

import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, Mail, LogOut, UserRound } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import '../../src/pulse-design-system.css';

const ACTOR_KEY = 'pulse:social:actor';

function currentActor() { if (typeof window === 'undefined') return ''; return window.localStorage.getItem(ACTOR_KEY) || ''; }
async function claimActor(userId) { const oldActor = currentActor(); if (!userId) return; if (oldActor && oldActor !== userId) { const { error } = await supabase.rpc('claim_actor_identity', { p_old_actor_id: oldActor, p_new_actor_id: userId }); if (error) throw error; } window.localStorage.setItem(ACTOR_KEY, userId); }

export default function AccountPage() {
  const [mode, setMode] = useState('create'); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [userEmail, setUserEmail] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  useEffect(() => { supabase.auth.getSession().then(({ data }) => setUserEmail(data.session?.user?.email || '')); }, []);
  const submit = async (event) => { event.preventDefault(); const cleanEmail = email.trim().toLowerCase(); if (!cleanEmail) return setError('Please enter an email address.'); if (password.length < 8) return setError('Use at least 8 characters.'); if (mode === 'create' && password !== confirm) return setError('Passwords do not match.'); setBusy(true); setError(''); setMessage(''); try { if (mode === 'create') { const { data, error: signUpError } = await supabase.auth.signUp({ email: cleanEmail, password, options: { emailRedirectTo: window.location.origin + '/' } }); if (signUpError) throw signUpError; if (data.session?.user) { await claimActor(data.session.user.id); setUserEmail(data.session.user.email || cleanEmail); setMessage('Your account is ready.'); } else setMessage('Check your email to finish creating the account.'); } else { const { data, error: signInError } = await supabase.auth.signInWithPassword({ email: cleanEmail, password }); if (signInError) throw signInError; if (data.user) { await claimActor(data.user.id); setUserEmail(data.user.email || cleanEmail); setMessage('You are signed in.'); } } } catch (e) { const text = String(e?.message || ''); if (text.toLowerCase().includes('email address not authorized')) setError('Supabase cannot send verification mail to this address right now.'); else if (text.toLowerCase().includes('already registered')) setError('That email is already registered. Try logging in.'); else if (text.toLowerCase().includes('invalid login credentials')) setError('The email or password is incorrect.'); else setError(text || 'Account action failed.'); } finally { setBusy(false); } };
  const logout = async () => { await supabase.auth.signOut(); window.location.href = '/'; };
  if (userEmail) return <main className="pulse-page account-v2"><header className="pulse-page-header"><div><div className="pulse-page-kicker"><UserRound size={12}/> ACCOUNT</div><h1 className="pulse-page-title">You're in.</h1><p className="pulse-page-subtitle">Your Pulse identity is connected to this account.</p></div><button className="precision-icon" onClick={() => { window.location.href = '/you'; }} aria-label="Back"><ArrowLeft size={17}/></button></header><section className="account-card"><span>CONNECTED ACCOUNT</span><strong>{userEmail}</strong><button className="precision-button secondary" onClick={logout}><LogOut size={15}/> LOG OUT</button></section></main>;
  return <main className="pulse-page account-v2"><header className="pulse-page-header"><div><div className="pulse-page-kicker"><UserRound size={12}/> ACCOUNT</div><h1 className="pulse-page-title">Keep your<br/>Pulse.</h1><p className="pulse-page-subtitle">Sign in so what you create and change stays with you.</p></div><button className="precision-icon" onClick={() => { window.location.href = '/'; }} aria-label="Back"><ArrowLeft size={17}/></button></header><div className="account-switch"><button className={mode === 'create' ? 'active' : ''} onClick={() => { setMode('create'); setError(''); setMessage(''); }}>CREATE</button><button className={mode === 'login' ? 'active' : ''} onClick={() => { setMode('login'); setError(''); setMessage(''); }}>LOG IN</button></div><form className="account-form" onSubmit={submit}><label><span>EMAIL</span><input type="email" autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com"/></label><label><span>PASSWORD</span><input type="password" autoComplete={mode === 'create' ? 'new-password' : 'current-password'} value={password} onChange={(e) => setPassword(e.target.value)} placeholder="8 characters or more"/></label>{mode === 'create'&&<label><span>CONFIRM PASSWORD</span><input type="password" autoComplete="new-password" value={confirm} onChange={(e)=>setConfirm(e.target.value)} placeholder="Enter it again"/></label>}{error&&<div className="account-error">{error}</div>}{message&&<div className="account-message"><Mail size={15}/>{message}</div>}<button className="pulse-join-primary" type="submit" disabled={busy}>{busy?'WORKING…':mode==='create'?'CREATE ACCOUNT':'LOG IN'} {!busy&&<ArrowRight size={15}/>}</button></form></main>;
}
