'use client';

import { AnimatePresence, motion } from 'framer-motion';
import { ArrowLeft, ArrowRight, Camera, GitCompare, History, MessageCircleQuestion, Target, X, Zap } from 'lucide-react';
import { useEffect, useMemo, useRef, useState } from 'react';
import { supabase } from '../lib/supabase';
import { ACTIONS, MAX_STEPS, START_TASK, generateNextTask, latestPayload, parsePayload, serializeStep, starterPayload } from '../lib/pulse-v2';

const HISTORY_KEY='pulse:v3:pulses'; const SESSION_KEY='pulse:v3:sessions'; const DEVICE_KEY='pulse:v4:creator-id';
function safeParse(v,f=null){try{return JSON.parse(v)}catch{return f}} function stepsOf(r){return Array.isArray(r?.steps)?r.steps:[]}
function readSessions(){if(typeof window==='undefined')return{};return safeParse(localStorage.getItem(SESSION_KEY)||'{}',{})} function readHistory(){if(typeof window==='undefined')return[];return safeParse(localStorage.getItem(HISTORY_KEY)||'[]',[])}
function saveSession(id,v){const a=readSessions();a[id]=v;localStorage.setItem(SESSION_KEY,JSON.stringify(a))} function saveHistory(e){const n=[e,...readHistory().filter(x=>x.id!==e.id)].slice(0,30);localStorage.setItem(HISTORY_KEY,JSON.stringify(n))}
function deviceId(){if(typeof window==='undefined')return'';let id=localStorage.getItem(DEVICE_KEY);if(!id){id=crypto.randomUUID();localStorage.setItem(DEVICE_KEY,id)}return id}
function payloadsOf(r){return stepsOf(r).map(s=>parsePayload(s?.output)).filter(Boolean)} function currentPayload(r){return latestPayload(r)||parsePayload(r?.seed)||null} function taskForRelay(r){return currentPayload(r)?.task||START_TASK}
function imageOf(p){return p?.artifact?.dataUrl||p?.result?.dataUrl||null} function previousImageOf(p){return p?.artifact?.previousDataUrl||null}
function textOf(p){return p?.artifact?.text||p?.result?.text||p?.result?.note||p?.result?.evidence||p?.result?.summary||''}
function actionIcon(a){if(a===ACTIONS.CHOOSE)return Target;if(a===ACTIONS.FIND||a===ACTIONS.CAPTURE)return Camera;if(a===ACTIONS.COMPARE)return GitCompare;if(a===ACTIONS.CHALLENGE)return MessageCircleQuestion;return Zap}
async function imageFileToDataUrl(file,maxSide=960,quality=.68){if(!file?.type?.startsWith('image/'))throw Error('画像を選んでください。');const source=await createImageBitmap(file);const scale=Math.min(1,maxSide/Math.max(source.width,source.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(source.width*scale));canvas.height=Math.max(1,Math.round(source.height*scale));const ctx=canvas.getContext('2d');if(!ctx)throw Error('画像を読み込めませんでした。');ctx.drawImage(source,0,0,canvas.width,canvas.height);source.close();return canvas.toDataURL('image/jpeg',quality)}
function PhotoFrame({dataUrl,marker,onMark,compact=false}){if(!dataUrl)return <div className={`grid aspect-[4/3] place-items-center rounded-[26px] border border-dashed border-[#24251f]/15 bg-[#f3efe5]/45 text-sm text-[#686b5b] ${compact?'min-h-28':''}`}>画像がここに表示されます</div>;return <div className={`relative aspect-[4/3] overflow-hidden rounded-[26px] bg-[#d6cdbb] ${onMark?'cursor-crosshair':''}`} onClick={e=>{if(!onMark)return;const r=e.currentTarget.getBoundingClientRect();onMark({x:(e.clientX-r.left)/r.width*100,y:(e.clientY-r.top)/r.height*100})}}><img src={dataUrl} alt="Pulse" className="block h-full w-full object-cover"/>{marker?<motion.div initial={{scale:.3,opacity:0}} animate={{scale:1,opacity:1}} className="absolute h-12 w-12 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-[#f8f4eb] bg-[#f8f4eb]/10 shadow-[0_0_0_5px_rgba(36,37,31,.26)]" style={{left:`${marker.x}%`,top:`${marker.y}%`}}/>:null}</div>}
function PrimaryButton({children,onClick,disabled,icon:Icon=ArrowRight}){return <button disabled={disabled} onClick={onClick} className="inline-flex items-center justify-center gap-3 rounded-full bg-[#24251f] px-6 py-3 text-sm font-semibold text-[#f3efe5] transition-transform hover:-translate-y-0.5 active:scale-[.98] disabled:pointer-events-none disabled:opacity-35">{children}<Icon size={17}/></button>}
function StepPill({action}){const Icon=actionIcon(action);const label=({CAPTURE:'撮る',FIND:'探す',CHOOSE:'選ぶ',INTERPRET:'別の見方',COMPARE:'比べる',CHALLENGE:'疑う',PREDICT:'予測する'})[action]||action;return <div className="inline-flex items-center gap-2 rounded-full border border-[#24251f]/12 bg-[#f3efe5]/72 px-3 py-1.5 text-[11px] font-bold uppercase tracking-[.15em]"><Icon size={13}/>{label}</div>}
function PreviousArtifact({payload}){const main=imageOf(payload);const previous=previousImageOf(payload);const text=textOf(payload);const marker=payload?.artifact?.marker||payload?.result?.marker;if(previous&&main)return <div className="grid grid-cols-2 gap-3"><PhotoFrame dataUrl={previous} compact/><PhotoFrame dataUrl={main} marker={marker} compact/></div>;if(main)return <PhotoFrame dataUrl={main} marker={marker} compact/>;if(text)return <div className="rounded-[24px] border border-[#24251f]/12 bg-[#f3efe5]/70 p-5 text-base leading-7">{text}</div>;return <div className="rounded-[24px] border border-dashed border-[#24251f]/15 bg-[#f3efe5]/45 p-5 text-sm text-[#686b5b]">前の人の成果物はテキストです。</div>}

export default function Page(){
 const [screen,setScreen]=useState('home'),[relay,setRelay]=useState(null),[role,setRole]=useState(''),[token,setToken]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[history,setHistory]=useState([]),[showHistory,setShowHistory]=useState(false),[creatorPhoto,setCreatorPhoto]=useState(''),[photo,setPhoto]=useState(''),[marker,setMarker]=useState(null),[text,setText]=useState(''),[compareNote,setCompareNote]=useState(''),[claim,setClaim]=useState(''),[challengeEvidence,setChallengeEvidence]=useState('');
 const creatorInputRef=useRef(null);const payload=useMemo(()=>currentPayload(relay),[relay]);const task=useMemo(()=>taskForRelay(relay),[relay]);const count=relay?.step_count??stepsOf(relay).length;const revealSteps=useMemo(()=>payloadsOf(relay),[relay]);const currentArtifact=imageOf(payload);
 useEffect(()=>{setHistory(readHistory())},[]);
 useEffect(()=>{const es=history.slice(0,12);if(!es.length)return;const cs=es.map(e=>supabase.channel(`pulse-history-${e.id}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'relays',filter:`id=eq.${e.id}`},({new:n})=>{saveHistory({id:n.id,role:e.role,status:n.status,stepCount:n.step_count??stepsOf(n).length,updatedAt:Date.now()});setHistory(readHistory());if(relay?.id===n.id)setRelay(n)}).subscribe());return()=>cs.forEach(c=>supabase.removeChannel(c))},[history,relay?.id]);
 useEffect(()=>{if(!relay?.id)return;const c=supabase.channel(`pulse-${relay.id}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'relays',filter:`id=eq.${relay.id}`},({new:n})=>{setRelay(n);saveHistory({id:n.id,role,status:n.status,stepCount:n.step_count??stepsOf(n).length,updatedAt:Date.now()});setHistory(readHistory());if(n.status==='complete')setScreen('result')}).subscribe();return()=>supabase.removeChannel(c)},[relay?.id,role]);
 function reset(){setScreen('home');setRelay(null);setRole('');setToken('');setCreatorPhoto('');setPhoto('');setMarker(null);setText('');setCompareNote('');setClaim('');setChallengeEvidence('');setError('');setShowHistory(false)}
 async function onPhotoPicked(e,setter){const f=e.target.files?.[0];e.target.value='';if(!f)return;try{setBusy(true);setError('');setter(await imageFileToDataUrl(f))}catch(err){setError(err?.message||'画像を読み込めませんでした。')}finally{setBusy(false)}}
 async function createPulse(){if(!creatorPhoto){setError('最初の写真を撮ってください。');return}setBusy(true);setError('');try{const{data,error:e}=await supabase.rpc('create_relay',{p_seed:JSON.stringify(starterPayload(creatorPhoto,deviceId()))});if(e)throw e;if(!data?.id)throw Error('Pulseを作れませんでした。');setRelay(data);setRole('creator');setToken('');saveSession(data.id,{role:'creator',token:''});saveHistory({id:data.id,role:'creator',status:data.status,stepCount:data.step_count??0,updatedAt:Date.now()});setHistory(readHistory());setScreen('waiting')}catch(err){setError(err?.message||'Pulseを作れませんでした。')}finally{setBusy(false)}}
 async function claimPulse(){setBusy(true);setError('');try{const{data,error:e}=await supabase.rpc('claim_relay',{p_exclude_creator_id:deviceId()});if(e)throw e;if(!data?.relay){setError('今は参加できるPulseがありません。');return}setRelay(data.relay);setRole('stranger');setToken(data.token);setPhoto('');setMarker(null);setText('');setCompareNote('');setClaim('');setChallengeEvidence('');setScreen('task');saveSession(data.relay.id,{role:'stranger',token:data.token});saveHistory({id:data.relay.id,role:'stranger',status:data.relay.status,stepCount:data.relay.step_count??0,updatedAt:Date.now()});setHistory(readHistory())}catch(err){setError(err?.message||'Pulseを見つけられませんでした。')}finally{setBusy(false)}}
 async function submitStep(){if(!relay||!token||busy)return;const action=task?.actionType,inputType=task?.inputType;let result={},nextArtifact=payload?.artifact||null;if(inputType==='tap'){if(!marker){setError('写真の中から1か所をタップしてください。');return}result={marker,summary:'写真の中の1点を選択した'};nextArtifact={...nextArtifact,marker}}else if(inputType==='text'){const clean=text.trim().replace(/\s+/g,' ');if(!clean||clean.length>(task.maxLength||120)){setError('短い一文で入力してください。');return}result={text:clean,summary:clean};nextArtifact={type:'text',text:clean}}else if(inputType==='compare'){const note=compareNote.trim().replace(/\s+/g,' ');if(!photo){setError('比較するための新しい写真を1枚追加してください。');return}if(!note||note.length>120){setError('違いを一文で書いてください。');return}result={dataUrl:photo,note,summary:note};nextArtifact={type:'compare',previousDataUrl:currentArtifact||null,dataUrl:photo,note}}else if(inputType==='challenge'){const c=claim.trim().replace(/\s+/g,' '),ev=challengeEvidence.trim().replace(/\s+/g,' ');if(!c||c.length>120){setError('疑っている主張を一文で書いてください。');return}if(!photo){setError('反証になりそうなものを1枚撮ってください。');return}if(!ev||ev.length>120){setError('なぜ反証になるのか一文で書いてください。');return}result={claim:c,dataUrl:photo,evidence:ev,summary:ev};nextArtifact={type:'challenge',dataUrl:photo,claim:c,evidence:ev}}else{if(!photo){setError('写真を1枚追加してください。');return}result={dataUrl:photo,summary:'新しい写真を1枚残した'};nextArtifact={type:'photo',dataUrl:photo,marker:null,text:null}}const currentStep=count+1,previous={...payload,action,result,artifact:nextArtifact,task},actionHistory=[...payloadsOf(relay).map(x=>x.action).filter(Boolean),action],nextTask=currentStep>=MAX_STEPS?null:generateNextTask({previous,history:actionHistory,seed:relay.id,step:currentStep+1}),output=serializeStep({artifact:nextArtifact,action,result,step:currentStep,task,nextTask});setBusy(true);setError('');try{const{data,error:e}=await supabase.rpc('submit_relay_step',{p_relay_id:relay.id,p_token:token,p_output:output});if(e)throw e;setRelay(data);setToken('');saveSession(relay.id,{role,token:''});saveHistory({id:data.id,role,status:data.status,stepCount:data.step_count??stepsOf(data).length,updatedAt:Date.now()});setHistory(readHistory());setPhoto('');setMarker(null);setText('');setCompareNote('');setClaim('');setChallengeEvidence('');setScreen(data.status==='complete'||!nextTask?'result':'waiting')}catch(err){setError(err?.message||'Pulseを次へ渡せませんでした。')}finally{setBusy(false)}}
 async function resume(entry){setBusy(true);setError('');try{const{data,error:e}=await supabase.from('relays').select('*').eq('id',entry.id).maybeSingle();if(e||!data)throw e||Error('そのPulseはもうありません。');const s=readSessions()[entry.id]||{};setRelay(data);setRole(entry.role||s.role||'creator');setToken(s.token||'');setShowHistory(false);setScreen(data.status==='complete'?'result':s.token?'task':'waiting')}catch(err){setError(err?.message||'そのPulseを開けませんでした。')}finally{setBusy(false)}}
 function renderInput(){const type=task?.inputType;if(type==='tap')return <div className="space-y-4"><PhotoFrame dataUrl={currentArtifact} marker={marker} onMark={setMarker}/><p className="text-sm text-[#686b5b]">写真の上をタップ。選んだ場所が次の流れに残ります。</p></div>;if(type==='text')return <div className="rounded-[26px] border border-[#24251f]/12 bg-[#f3efe5]/70 p-5"><div className="mb-3 flex items-center justify-between text-[11px] font-bold uppercase tracking-[.18em] text-[#686b5b]"><span>your input</span><span>{text.length}/120</span></div><textarea value={text} onChange={e=>setText(e.target.value)} maxLength={120} rows={5} placeholder={task.actionType===ACTIONS.PREDICT?'次に見つかりそうなものを一文で予測':'一文で残す'} className="w-full resize-none bg-transparent text-lg leading-8 outline-none placeholder:text-[#686b5b]/45"/></div>;if(type==='compare')return <div className="space-y-4"><div className="grid grid-cols-2 gap-3"><PhotoFrame dataUrl={currentArtifact} compact/><PhotoFrame dataUrl={photo} compact/></div><label className="block rounded-[24px] border border-[#24251f]/12 bg-[#f3efe5]/70 p-5"><span className="mb-2 block text-[11px] font-bold uppercase tracking-[.18em] text-[#686b5b]">difference</span><textarea value={compareNote} onChange={e=>setCompareNote(e.target.value)} maxLength={120} rows={3} placeholder="違いを一文で" className="w-full resize-none bg-transparent text-base leading-7 outline-none"/></label><button onClick={()=>document.getElementById('pulse-photo-input')?.click()} className="rounded-full border border-[#24251f]/15 px-5 py-3 text-sm font-semibold">新しい写真を追加</button></div>;if(type==='challenge')return <div className="space-y-4"><label className="block rounded-[24px] border border-[#24251f]/12 bg-[#f3efe5]/70 p-5"><span className="mb-2 block text-[11px] font-bold uppercase tracking-[.18em] text-[#686b5b]">claim</span><textarea value={claim} onChange={e=>setClaim(e.target.value)} maxLength={120} rows={3} placeholder="疑っている主張を一文で" className="w-full resize-none bg-transparent text-base leading-7 outline-none"/></label><PhotoFrame dataUrl={photo} compact/><label className="block rounded-[24px] border border-[#24251f]/12 bg-[#f3efe5]/70 p-5"><span className="mb-2 block text-[11px] font-bold uppercase tracking-[.18em] text-[#686b5b]">evidence</span><textarea value={challengeEvidence} onChange={e=>setChallengeEvidence(e.target.value)} maxLength={120} rows={3} placeholder="なぜ反証になるのか一文で" className="w-full resize-none bg-transparent text-base leading-7 outline-none"/></label><button onClick={()=>document.getElementById('pulse-photo-input')?.click()} className="rounded-full border border-[#24251f]/15 px-5 py-3 text-sm font-semibold">反証の写真を追加</button></div>;return <div className="space-y-4"><PhotoFrame dataUrl={photo} compact/><button onClick={()=>document.getElementById('pulse-photo-input')?.click()} className="rounded-full border border-[#24251f]/15 px-5 py-3 text-sm font-semibold">写真を追加</button></div>}
 return <main className="min-h-screen bg-[#e8e1d2] text-[#24251f]"><input id="pulse-photo-input" type="file" accept="image/*" capture="environment" className="hidden" onChange={e=>onPhotoPicked(e,setPhoto)}/><div className="mx-auto min-h-screen w-full max-w-xl px-5 py-6 sm:px-7"><header className="mb-8 flex items-center justify-between"><button onClick={reset} className="text-2xl font-black tracking-[-.06em]">PULSE</button><button onClick={()=>setShowHistory(true)} className="rounded-full border border-[#24251f]/12 bg-[#f3efe5]/60 p-3"><History size={17}/></button></header><AnimatePresence mode="wait">
 {screen==='home'&&<motion.section key="home" initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className="flex min-h-[70vh] flex-col justify-center"><p className="mb-4 text-[11px] font-bold uppercase tracking-[.22em] text-[#686b5b]">A relay through strangers</p><h1 className="max-w-lg text-5xl font-black leading-[.98] tracking-[-.055em] sm:text-6xl">世界の「まだ知らない」を、<br/>1タップで発見。</h1><p className="mt-7 max-w-md text-base leading-7 text-[#55584c]">誰かの一手が、次の人のやることを変える。5人でひとつのPulseを作ります。</p><div className="mt-10 flex flex-wrap gap-3"><PrimaryButton onClick={claimPulse} disabled={busy}>参加する</PrimaryButton><button onClick={()=>{setCreatorPhoto('');setError('');setScreen('create')}} className="rounded-full border border-[#24251f]/15 bg-[#f3efe5]/55 px-6 py-3 text-sm font-semibold">最初の一手を作る</button></div></motion.section>}
 {screen==='create'&&<motion.section key="create" initial={{opacity:0,y:10}} animate={{opacity:1,y:0}}><button onClick={reset} className="mb-6 inline-flex items-center gap-2 text-sm text-[#686b5b]"><ArrowLeft size={16}/>戻る</button><StepPill action={ACTIONS.CAPTURE}/><h2 className="mt-5 text-3xl font-black">最初の一枚。</h2><p className="mt-3 text-sm leading-6 text-[#686b5b]">{START_TASK.prompt}</p><div className="mt-7"><PhotoFrame dataUrl={creatorPhoto}/></div><div className="mt-5 flex gap-3"><button onClick={()=>creatorInputRef.current?.click()} className="rounded-full border border-[#24251f]/15 px-5 py-3 text-sm font-semibold">写真を選ぶ</button><PrimaryButton onClick={createPulse} disabled={busy||!creatorPhoto}>Pulseを作る</PrimaryButton></div><input ref={creatorInputRef} type="file" accept="image/*" capture="environment" className="hidden" onChange={e=>onPhotoPicked(e,setCreatorPhoto)}/></motion.section>}
 {screen==='task'&&<motion.section key="task" initial={{opacity:0,y:10}} animate={{opacity:1,y:0}}><div className="mb-6 flex items-center justify-between"><StepPill action={task.actionType}/><span className="text-xs font-semibold text-[#686b5b]">{count+1} / {MAX_STEPS}</span></div><div className="rounded-[28px] border border-[#24251f]/10 bg-[#f3efe5]/55 p-5"><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#686b5b]">PREVIOUS MOVE</p><div className="mt-4"><PreviousArtifact payload={payload}/></div><p className="mt-5 text-[10px] font-black uppercase tracking-[.2em] text-[#686b5b]">THEIR TASK</p><p className="mt-2 text-sm leading-6">{payload?.performedTask?.prompt||(payload?.step===0?START_TASK.prompt:'前の人の一手')}</p><p className="mt-5 text-[10px] font-black uppercase tracking-[.2em] text-[#686b5b]">YOUR TASK</p><h2 className="mt-2 text-2xl font-black">{task?.title}</h2><p className="mt-2 text-base leading-7">{task?.prompt}</p><p className="mt-2 text-sm leading-6 text-[#686b5b]">{task?.hint}</p></div><div className="mt-5">{renderInput()}</div><div className="mt-6 flex justify-end"><PrimaryButton onClick={submitStep} disabled={busy}>{busy?'渡しています…':'次へ渡す'}</PrimaryButton></div></motion.section>}
 {screen==='waiting'&&<motion.section key="waiting" initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className="flex min-h-[65vh] flex-col justify-center"><div className="rounded-[32px] border border-[#24251f]/10 bg-[#f3efe5]/55 p-7"><p className="text-[11px] font-bold uppercase tracking-[.2em] text-[#686b5b]">PULSE {count} / {MAX_STEPS}</p><h2 className="mt-4 text-4xl font-black">次の人を待っています。</h2><p className="mt-4 text-sm leading-7 text-[#686b5b]">誰かが一手を残すと、このPulseが進みます。</p><div className="mt-8 h-2 overflow-hidden rounded-full bg-[#24251f]/10"><motion.div className="h-full rounded-full bg-[#24251f]" animate={{width:`${Math.min(100,count/MAX_STEPS*100)}%`}}/></div><button onClick={reset} className="mt-8 rounded-full border border-[#24251f]/15 px-5 py-3 text-sm font-semibold">ホームへ</button></div></motion.section>}
 {screen==='result'&&<motion.section key="result" initial={{opacity:0,y:10}} animate={{opacity:1,y:0}}><p className="text-[11px] font-bold uppercase tracking-[.2em] text-[#686b5b]">REVEAL</p><h2 className="mt-3 text-5xl font-black">このPulseは、<br/>こう変わった。</h2><div className="mt-8 space-y-4">{revealSteps.map((s,i)=><div key={`${i}-${s.action}`} className="rounded-[28px] border border-[#24251f]/10 bg-[#f3efe5]/60 p-5"><div className="flex items-center justify-between"><StepPill action={s.action}/><span className="text-xs text-[#686b5b]">{i+1}</span></div><div className="mt-4"><PreviousArtifact payload={s}/></div>{textOf(s)?<p className="mt-4 text-sm leading-6 text-[#55584c]">{textOf(s)}</p>:null}</div>)}</div><button onClick={reset} className="mt-7 rounded-full border border-[#24251f]/15 px-5 py-3 text-sm font-semibold">ホームへ戻る</button></motion.section>}
 {showHistory&&<motion.div key="history" initial={{opacity:0}} animate={{opacity:1}} className="fixed inset-0 z-50 bg-[#24251f]/25 p-4 sm:p-8" onClick={()=>setShowHistory(false)}><div className="mx-auto mt-10 max-w-xl rounded-[30px] bg-[#f3efe5] p-6" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between"><h2 className="text-2xl font-black">履歴</h2><button onClick={()=>setShowHistory(false)} className="rounded-full p-2"><X size={18}/></button></div><div className="mt-5 space-y-2">{history.length?history.map(e=><button key={e.id} onClick={()=>resume(e)} className="flex w-full items-center justify-between rounded-2xl border border-[#24251f]/10 bg-white/35 px-4 py-4 text-left"><span><span className="block text-sm font-semibold">{e.role==='creator'?'自分が作ったPulse':'参加したPulse'}</span><span className="text-xs text-[#686b5b]">{e.stepCount??0} / {MAX_STEPS} · {e.status}</span></span><ArrowRight size={16}/></button>):<p className="py-8 text-center text-sm text-[#686b5b]">まだ履歴はありません。</p>}</div></div></motion.div>}
 </AnimatePresence>{error?<div className="fixed bottom-5 left-1/2 z-[60] w-[calc(100%-32px)] max-w-xl -translate-x-1/2 rounded-2xl border border-[#8b3f2f]/20 bg-[#f7e5dc] px-4 py-3 text-sm text-[#6b3025]">{error}</div>:null}</div></main>
}
