'use client';
import { useEffect,useMemo,useState } from 'react';
import Link from 'next/link';
import { Compass,ArrowRight } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import { seedFromPulse,contentFromMove,formatRelative } from '../../lib/pulse-social';
import '../../src/pulse-ui-v1.css';
function Card({p}){const seed=seedFromPulse(p);return <Link className="pulse-card-link" href={`/pulse/${p.id}`}><article className="precision-card pad"><div className="pulse-card-top"><span className="pulse-move-chip live">{p.status==='active'?'MOVING':'REVEALED'}</span><span className="precision-label">{formatRelative(p.updated_at)}</span></div><h2 className="pulse-card-title-xl">{p.title}</h2><div className="pulse-card-state"><div className="precision-label">CURRENT STATE</div><p>{seed?.text||'Something is waiting to change.'}</p></div><div className="pulse-card-join"><span className="pulse-card-join-copy">{p.intent||'Join the next move and change what happens.'}</span><span className="precision-button">OPEN <ArrowRight size={14}/></span></div></article></Link>}
export default function Explore(){const [pulses,setPulses]=useState([]);const [query,setQuery]=useState('');const [filter,setFilter]=useState('MOVING');useEffect(()=>{supabase.from('pulses').select('*').order('updated_at',{ascending:false}).limit(50).then(({data})=>setPulses(data||[]))},[]);const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return pulses.filter(p=>(filter==='MOVING'?p.status==='active':filter==='FRESH'?true:true)&&(!q||`${p.title} ${p.intent||''}`.toLowerCase().includes(q)))},[pulses,query,filter]);return <main className="pulse-page"><header className="pulse-page-header"><div><div className="pulse-page-kicker">PULSE / DISCOVERY</div><h1 className="pulse-page-title">Find your<br/>next move.</h1><p className="pulse-page-subtitle">Search by idea, intent, or the state a Pulse is creating.</p></div></header><div className="pulse-segment"><button aria-pressed={filter==='MOVING'} onClick={()=>setFilter('MOVING')}>MOVING</button><button aria-pressed={filter==='FRESH'} onClick={()=>setFilter('FRESH')}>FRESH</button><button aria-pressed={filter==='ALL'} onClick={()=>setFilter('ALL')}>ALL</button></div><input aria-label="Search Pulses" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search title or intent…" style={{width:'100%',height:48,padding:'0 15px',marginBottom:18,border:'1px solid var(--pulse-line)',borderRadius:17,background:'#fff',outline:'none'}}/><div className="pulse-grid pulse-grid-3">{filtered.map(p=><Card key={p.id} p={p}/>)}</div></main>}
