'use client';
import { motion } from 'framer-motion';
import { ArrowUpRight, Footprints, GitBranch } from 'lucide-react';
import type { Post } from '@/types/pulse';
import { AsyncMedia } from '@/components/ui/AsyncMedia';

export function ActionCard({ post, index = 0, onOpen }: { post: Post; index?: number; onOpen?: (post: Post) => void }) {
  const media = post.media[0]; const author = post.author; const handoff = post.handoff_from;
  return <motion.article initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .06 }} className="group overflow-hidden rounded-[28px] border border-white/[.07] bg-[#101013] shadow-[0_24px_80px_rgba(0,0,0,.22)]">
    <div className="grid lg:grid-cols-[1.02fr_.98fr]">
      <div className="relative min-h-[300px] overflow-hidden bg-[#0b0b0d] lg:min-h-[440px]">{media?.url ? <div className="h-full transition-transform duration-700 group-hover:scale-[1.025]"><AsyncMedia src={media.url} alt={media.alt ?? post.title} width={media.width} height={media.height} /></div> : <div className="h-full min-h-[300px] bg-[#111114]" />}<div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-black/45 via-transparent to-transparent" /><div className="absolute left-5 top-5 rounded-full bg-black/45 px-3 py-1.5 text-[10px] font-medium uppercase tracking-[.18em] text-white/80 backdrop-blur-md">Active Pulse // {String(post.pulse_number ?? index + 1).padStart(2,'0')}</div></div>
      <div className="flex flex-col justify-between p-6 sm:p-8 lg:p-10"><div><div className="flex items-center justify-between gap-4 text-[10px] uppercase tracking-[.18em] text-zinc-500"><span className="text-zinc-300">Live question</span><span>{post.handoff_count ?? 0} people changed this</span></div><h2 className="mt-7 max-w-xl text-[clamp(1.8rem,3vw,3.15rem)] font-medium leading-[1.02] tracking-[-.04em] text-zinc-50">{post.title}</h2><div className="mt-8 rounded-2xl bg-white/[.035] p-5 ring-1 ring-white/[.05]"><div className="flex items-center gap-2 text-[10px] uppercase tracking-[.18em] text-zinc-500"><Footprints size={13}/> Your next move</div><p className="mt-3 text-sm leading-6 text-zinc-200">{post.action ?? post.description}</p></div><div className="mt-6 flex items-center gap-3">{handoff?.avatar_url ? <img src={handoff.avatar_url} alt="" className="h-8 w-8 rounded-full object-cover"/> : <div className="h-8 w-8 rounded-full bg-white/10"/>}<div><p className="text-[10px] uppercase tracking-[.16em] text-zinc-500">Signal from</p><p className="text-sm text-zinc-200">@{handoff?.username ?? author?.username ?? 'pulse'} <span className="px-1 text-zinc-700">→</span> <span className="text-zinc-400">Next Action</span></p></div><GitBranch size={15} className="ml-auto text-zinc-600"/></div></div><div className="mt-10 flex flex-wrap gap-3"><button type="button" onClick={() => onOpen?.(post)} className="inline-flex items-center gap-2 rounded-full bg-zinc-100 px-5 py-3 text-xs font-semibold uppercase tracking-[.14em] text-zinc-950"><Footprints size={14}/> Take action</button><button type="button" onClick={() => onOpen?.(post)} className="inline-flex items-center gap-2 rounded-full border border-white/[.09] px-5 py-3 text-xs font-semibold uppercase tracking-[.14em] text-zinc-200">Join this Pulse <ArrowUpRight size={14}/></button></div></div>
    </div>
  </motion.article>;
}
